apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: v1.34.0
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - resources/layer2Announcements.yaml
  - resources/loadBalancerIpAddressManagement.yaml
  - resources/allowIstioHealthProbes.yaml
