---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-options
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            securityContext:
              seccompProfile:
                type: "RuntimeDefault"
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-options
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            securityContext:
              seccompProfile:
                type: "RuntimeDefault"
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-options
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            securityContext:
              seccompProfile:
                type: "RuntimeDefault"
...
