apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: v1.10.1
    namespace: longhorn-system
    includeCRDs: true
    valuesFile: values.yaml
