apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: 1.6.2
    namespace: envoy-gateway-system
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - resources/proxyHuntInternalDevelopmentHome.yaml
  - resources/proxyHuntInternalDevelopmentLab.yaml
  - resources/proxyHuntInternalProductionHome.yaml
  - resources/proxyHuntInternalProductionLab.yaml
