apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: gateway-crds-helm
    repo: oci://docker.io/envoyproxy
    version: 1.6.3
    includeCRDs: true
    valuesFile: valuesEnvoyGateway.yaml
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml # gateway api standard channel
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml # gateway api experimental channel
