apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-api
resources:
  - resources/huntInternalDevelopmentHomeTlsTerminationCertificate.yaml
  - resources/huntInternalDevelopmentLabTlsTerminationCertificate.yaml
  - resources/gatewayHuntInternalDevelopmentHome.yaml
  - resources/gatewayHuntInternalDevelopmentLab.yaml
  - resources/routeHttpToHttpsRedirect.yaml
  # do NOT include a - ../../base/  because we don't want to clone the envs.
  # we just want to logically separate the envs but they all have to tie back to
  # the one gateway api class.
