apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-corefile
data:
  Corefile: |
    hunt.internal {
      cache 30
      errors
      file /zones/dbHuntInternal
      health # only set 1 time for all the zones. its a global setting.
      loadbalance
      log
      loop
      ready
      reload
    }
    . {
      cache 30
      errors
      forward . 1.1.1.1 8.8.8.8
      loadbalance
      log
      loop
      ready
      reload
    }
