apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-zonefile
data:
  dbHuntInternal: |
    hunt.internal. 3600 IN SOA dns.production.home.hunt.internal. localhost.hunt.internal. (
        1       ; Serial number
        60      ; Refresh     - every minute
        300     ; Retry       - every 5 minutes
        86400   ; Expire      - 24 hours
        30 )    ; Minimum TTL - 1 hour
    dns.production.home.hunt.internal. 30 IN A 192.168.20.90
