apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-zonefile
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  db.hunt.internal: | # <-- this is the name of the file that gets written to disk. file content is below.
    $TTL 30 ; default TTL
    $ORIGIN hunt.internal. ; base domain name
    ; start of authority rr defining the key characteristics of the zone (domain)
    @ IN SOA ns1.hunt.internal. internal-email.hunt.internal. (
      6     ; serial number - change this number each time a change is made or else coredns won't pick up the change
      60    ; refresh       - every minute
      300   ; update retry  - every 5 minutes
      86400 ; expiry        - 24 hours
      30    ; minimum ttl   - 1 hour
      )
             IN NS ns1.hunt.internal. ; name server rr for the domain
    ns1      IN A 192.168.30.2
    argocd   IN A 192.168.30.20
    longhorn IN A 192.168.30.20

# dont forget... serial number - change this number each time a change is made or else coredns won't pick up the change
