apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coredns-hunt-internal
resources:
  - resources/configmapCorefile.yaml
  - resources/configmapZonefile.yaml
  - resources/service.yaml
  - resources/deployment.yaml
