apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/argocd.yaml
  - resources/certManager.yaml
  - resources/coredns.yaml
  - resources/default.yaml
  - resources/istio.yaml
  - resources/longhorn.yaml
  - resources/metalLb.yaml
  - resources/infrastructure.yaml
