apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/certManager.yaml
  - resources/envoyGateway.yaml
  - resources/gatewayApi.yaml
  - resources/longhorn.yaml
  - resources/coredns.yaml

# Other namespaces
# argocd            is created when the cluster is bootstrapped initially
# cilium-secrets    is created when the cluster is bootstrapped initially
