apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts/
    targetRevision: v38.0.1
    chart: traefik
    helm:
      valuesObject: # using this instead of the values.yaml file since the file was not working. https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
        api:
          dashboard: true # enable the dashboard
        service:
          type: LoadBalancer # needs to be 'loadbalancer' so that the traefik service receives an ip address from cilium lb ipam
        global:
          checkNewVersion: false
          sendAnonymousUsage: false
        ingressClass:
          enabled: false # create a default IngressClass for traefik
        gatewayClass:
          enabled: false # when providers.kubernetesGateway.enabled and gateway.enabled, deploy a default gatewayClass
        gateway:
          enabled: false # when providers.kubernetesGateway.enabled, deploy a default gateway
        providers:
          kubernetesGateway: # we are ONLY using gateway api
            enabled: true # enable traefik gateway provider for gateway api
            nativeLBByDefault: true # defines whether to use native kubernetes load-balancing mode by default. - uses the service's ip
          kubernetesCRD:
            enabled: false # load kubernetes IngressRoute provider
          kubernetesIngress:
            enabled: false # load kubernetes Ingress provider
          kubernetesIngressNginx:
            enabled: false # enable kubernetes Ingress NGINX provider (experimental)
          knative:
            enabled: false # enable Knative provider
          file:
            enabled: false # create a file provider
        rbac:
          enabled: true
        ports: # these need to exist for the gateway api 'gateway listeners'
          web:
            port: 80
          websecure:
            port: 443
            http:
              sanitizePath: true
            tls:
              enabled: true
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
    syncOptions:
      - CreateNamespace=true
