apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-api
helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: 1.6.3
    namespace: gateway-api
    includeCRDs: true
    valuesFile: values.yaml
