apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/gatewayClass.yaml
  - resources/gatewayHuntInternalDevelopmentHome.yaml
  - resources/gatewayHuntInternalDevelopmentLab.yaml
  - resources/gatewayHuntInternalProductionHome.yaml
  - resources/gatewayHuntInternalProductionLab.yaml
  - resources/routeArgocd.yaml
    - resources/routeCoredns.yaml
  - resources/routeLonghorn.yaml
  - resources/routeHttpToHttpsRedirect.yaml
