apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/
resources:
  - resources/loadBalancerIpAddressManagement.yaml
  - resources/layer2Announcements.yaml
  - resources/routeCiliumHubble.yaml
